server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    session:
      timeout: 30m
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 10
  error:
    path: /error

file:
  upload-dir: ./uploads
  static-access-path: /uploads/**

Fit:
  captcha-open: true #是否开启登录时验证码 (true/false)

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fit?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: mysql-pool
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: select 1
      validation-timeout: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      readOnly: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: html/**,static/**,templates/**,mapper/**
  main:
    allow-circular-references: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    converters:
      preferred-json-mapper: fastjson
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  thymeleaf:
    cache: true
    check-template: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - classpath:/html/
        - file:${file.upload-dir}

mybatis:
  configuration:
    cache-enabled: true
    default-executor-type: REUSE
    use-generated-keys: true
  type-aliases-package: com.fit.entity
  mapper-locations: classpath:mapper/**/*.xml

logging:
  file:
    path: ./target/logs
  level:
    web: info
debug: false